name: nanoGPTQ
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12.12
  - pip=25.3

  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - numpy=1.26.4
  
  - beartype=0.22.7
  - requests=2.32.5
  - pyyaml=6.0.3
  - pillow=11.3.0
  - pytest=9.0.2